aaaaaa

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -15,15 +15,6 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Debug Secret Availability
-        run: |
-          if [ -z "${{ secrets.COOLIFY_WEBHOOK }}" ]; then
-            echo "SECRET IS EMPTY"
-            exit 1
-          else
-            echo "SECRET IS LOADED (Length: ${#SECRET})"
-          fi
-
       - name: Log in to the Container registry
         uses: docker/login-action@v3
         with:
@@ -44,5 +35,15 @@ jobs:
           cache-to: type=gha,mode=max
 
       - name: Trigger Coolify Deployment
+        env:
+          WEBHOOK_URL: ${{ secrets.COOLIFY_WEB_HOOK }}
+          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
         run: |
-          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
+          if [ -z "$WEBHOOK_URL" ]; then
+            echo "Error: WEBHOOK_URL is empty. Check your secret name in GitHub!"
+            exit 1
+          fi
+          curl --request GET "$WEBHOOK_URL" \
+               --header "Authorization: Bearer $COOLIFY_TOKEN"
+
+
